---
ID: "9bc0d524-b849-4afb-af45-682e742786a5"
Parent: "0356a408-d1b6-4236-acb5-cfeb40db12ee"
Template: "0356a408-d1b6-4236-acb5-cfeb40db12ee"
Path: /sitecore/templates/Project/VisitUs/Pages/Listings/Places/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{3F791D33-A796-447E-9F89-903A05E70DCD}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{029B416A-1100-4F83-85E7-79EB996DDADC}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220212T092337Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
